#!/bin/bash
read -p 'Do you wish to configure Geany? [y/N] ' responce
case $responce in
  y|Y)
    while [ ! -d "$homedir" ]
    do
    read -p 'Specify full path to your home directory: ' homedir
    if [ ! -d "$homedir" ]
      then
        echo 'Incorrect path. Try again.'
    fi
    done
    configfile="$homedir/.config/geany/filedefs/filetypes.pascal"
    mkdir -p "$homedir/.config/geany/filedefs"
    touch "$configfile"
    cat > "$configfile" <<- EOM
[build-menu]
FT_00_LB=_Скомпилировать
FT_00_CM=pabcnetc "%f"
FT_00_WD=
EX_00_LB=_Выполнить
EX_00_CM=mono "./%e.exe"
EX_00_WD='
EOM
    exit 0
    ;; 
  *)
    exit 0 ;;
esac