#!/bin/bash
read -p 'Do you wish to configure Geany? [y/N] ' responce
case $responce in
  y|Y)
    username='pascalabcnet'
    while [ ! -d "/home/$username" ]
    do
    read -p 'Specify your username: ' username
    if [ ! -d "/home/$username" ]
      then
        echo 'Incorrect username. Try again.'
    fi
    done
    configfile="/home/$username/.config/geany/filedefs/filetypes.pascal"
    mkdir -p "/home/$username/.config/geany/filedefs"
    touch "$configfile"
    cat > "$configfile" <<- EOM
[build-menu]
FT_00_LB=_Скомпилировать
FT_00_CM=pabcnetcclear "%f"
FT_00_WD=
EX_00_LB=_Выполнить
EX_00_CM=mono "./%e.exe"
EX_00_WD=
EOM
    chown -R "$username":"$username" "/home/$username/.config/geany/"
    exit 0
    ;; 
  *)
    exit 0 ;;
esac
